openapi: 3.0.0
info:
  contact: {}
servers:
- url: https://virtserver.swaggerhub.com/peterxcli/ncku-bikefest-2024/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /event:
    get:
      tags:
      - Event
      summary: Get all events
      description: Retrieves a list of all events with pagination
      parameters:
      - name: page
        in: query
        description: Page number for pagination
        required: false
        style: form
        explode: true
      - name: limit
        in: query
        description: Number of items per page for pagination
        required: false
        style: form
        explode: true
      responses:
        "200":
          description: List of events
        "500":
          description: Internal Server Error
    post:
      tags:
      - Event
      summary: Subscribe to an event
      description: Subscribes a user to an event with the provided details
      parameters:
      - name: user_id
        in: header
        description: User ID
        required: true
        style: simple
        explode: false
      responses:
        "200":
          description: Successfully subscribed to the event
        "400":
          description: Bad Request - Invalid input
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
  /event/{id}:
    get:
      tags:
      - Event
      summary: Get event by ID
      description: Retrieves an event using its unique ID
      parameters:
      - name: id
        in: path
        description: Event ID
        required: true
        style: simple
        explode: false
      responses:
        "200":
          description: Event successfully retrieved
        "500":
          description: Internal Server Error
    put:
      tags:
      - Events
      summary: Update an event
      description: Updates an event by ID with new details
      parameters:
      - name: id
        in: path
        description: Event ID
        required: true
        style: simple
        explode: false
      responses:
        "200":
          description: Event successfully updated
        "400":
          description: Bad Request - Invalid input
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
  /event/user:
    get:
      tags:
      - Event
      summary: Get User Events
      description: Retrieves a list of events associated with a user
      responses:
        "200":
          description: List of events associated with the user
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth // include this line if the endpoint is protected by an API key or other security mechanism: []
  /events/{event_id}:
    delete:
      tags:
      - Event
      summary: Delete event
      description: Deletes a specific event by its ID for a given user
      parameters:
      - name: user_id
        in: header
        description: User ID
        required: true
        style: simple
        explode: false
      - name: event_id
        in: path
        description: Event ID
        required: true
        style: simple
        explode: false
      responses:
        "200":
          description: Event successfully deleted
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
  /user/{user_id}:
    get:
      tags:
      - User
      summary: Get user by ID
      description: Retrieves a user's information by their ID
      parameters:
      - name: user_id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
      responses:
        "200":
          description: User successfully retrieved
        "500":
          description: Internal Server Error
  /user/login/{user_id}:
    get:
      tags:
      - User
      summary: Fake Login
      description: Simulates a login process for a user by generating fake access
        and refresh tokens
      parameters:
      - name: user_id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
      responses:
        "200":
          description: "Login successful, tokens generated"
        "500":
          description: Internal Server Error
  /user/logout:
    post:
      tags:
      - User
      summary: User logout
      description: Logs out a user by invalidating their authentication token
      parameters:
      - name: Authorization
        in: header
        description: "Bearer [token]"
        required: true
        style: simple
        explode: false
      responses:
        "200":
          description: Logout successful
        "401":
          description: "Unauthorized: Invalid token format"
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
  /user/profile:
    get:
      tags:
      - User
      summary: Profile
      description: Fetches the profile of a user
      parameters:
      - name: user_id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
      responses:
        "200":
          description: Profile successfully retrieved
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
  /user/refresh_token:
    post:
      tags:
      - Authentication
      summary: Refresh User Token
      description: Refreshes the access and refresh tokens for a user
      parameters: []
      responses:
        "200":
          description: Access and Refresh Tokens successfully generated
        "400":
          description: Bad Request - Invalid request format
        "401":
          description: Unauthorized - Invalid or expired refresh token
        "500":
          description: Internal Server Error - Error generating tokens
  /user/register:
    post:
      tags:
      - User
      summary: Fake Register
      description: Register a fake user for testing purposes
      parameters: []
      responses:
        "200":
          description: Fake register successful
        "400":
          description: Bad Request - Invalid input data
        "500":
          description: Internal Server Error
  /users:
    get:
      tags:
      - User
      summary: Get Users
      description: Retrieves a list of users
      responses:
        "200":
          description: List of users successfully retrieved
        "500":
          description: Internal Server Error
components: {}
